/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.lee;

import com.alibaba.excel.EasyExcel;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

public class ExcelReader {

    ExcelDataListener listener = new ExcelDataListener();
    private File excel;
    private List<String> heads;
    private List<String> rows;

    ExcelReader(File excel){
        this.excel = excel;
        this.heads = new ArrayList<>();
        this.rows = new ArrayList<>();
    }

    public List<String> getHeads(){
        return listener.getHeads();
    }

    public List<ExcelData> getRows(){
        return listener.getRows();
    }

    public void readAll(){
        EasyExcel.read(excel, ExcelData.class, listener).sheet().doRead();
    }
}
